 --Combines the full name of the person with their login info
 
 SELECT UPPER(FullName) + ' ' + UPPER(LogonName) AS FullName

FROM   Application.People

--Sample Output
--FullName
--DATA CONVERSION ONLY NO LOGON
--KAYLA WOODCOCK KAYLAW@WIDEWORLDIMPORTERS.COM
--HUDSON ONSLOW HUDSONO@WIDEWORLDIMPORTERS.COM
--ISABELLA RUPP ISABELLAR@WIDEWORLDIMPORTERS.COM
--EVA MUIRDEN EVAM@WIDEWORLDIMPORTERS.COM
